version: '3'
secrets:
    WeatherAPIKey:
      file: ../secret.py
services:
  kafka:
    build:
      context: ./
      dockerfile: KafkaDockerfile.txt
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  zookeeper: 
    image: wurstmeister/zookeeper:latest
    ports: 
      -  "2181:2181"

  producer:
    build:
      context: ../
      dockerfile: ./docker/ProducerDockerfile.txt
    secrets:
      - WeatherAPIKey
    depends_on:
      - kafka
    environment:
      KAFKA_BOOTSTRAP_SERVER: kafka:9092
      KAFKA_TOPIC: weather-data
      OTHER_ENV_VARIABLES: "if needed"


  consumer:
    build:
      context: ../
      dockerfile: ./docker/ConsumerDockerfile.txt
    depends_on:
      - kafka
    environment:
      KAFKA_BOOTSTRAP_SERVER: kafka:9092
      KAFKA_TOPIC: weather-data
      OTHER_ENV_VARIABLES: "if needed"
